enabled: true
blog_theme: dark
dropdown:
  enabled: true
scrollappear_enabled: true
summary_enabled: 'on'
header_font: cormorant
body_width: null
footer_text: 'Chalk Theme - A Grav port of Jekyll''s Chalk theme, made by Nielsen Ramon. Grav port by <a href="https://github.com/paulmassen">Paul Massendari</a>'
social_twitter: null
social_facebook: null
social_medium: null
social_github: null
social_gitlab: null
social_bitbucket: null
social_stackoverflow: null
social_keybase: null
social_docker: null
social_linkedin: null
social_dribbble: null
social_spotify: null
social_youtube: null
social_twitch: null
social_steam: null
social_discord: null
social_bitcoin: null
social_ethereum: null
social_email: null
social_flickr: null
social_instagram: null
social_tumblr: null
